name: Check Prometheus Helm Chart Version

on: [push]
  #schedule:
   # - cron: '0 9 * * 1'  # Every Monday 9 AM UTC
  #workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  check-prometheus-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Check Prometheus Helm Chart Version
      run: bash .github/scripts/check-prometheus-helm-version.sh

    - name: Create JIRA ticket if new version found
      if: env.IS_NEW_VERSION == 'true'
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        NEW_VERSION: ${{ env.NEW_VERSION }}
      run: |
        SUMMARY="Update Prometheus Helm Chart to version $NEW_VERSION"
        DESCRIPTION="A new version of the Prometheus Helm chart is available: $NEW_VERSION. Please update accordingly."

        curl -X POST -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
          -H "Content-Type: application/json" \
          --url "$JIRA_BASE_URL/rest/api/2/issue" \
          -d "{
            \"fields\": {
              \"project\": {
                \"key\": \"$JIRA_PROJECT_KEY\"
              },
              \"summary\": \"$SUMMARY\",
              \"description\": \"$DESCRIPTION\",
              \"issuetype\": {
                \"name\": \"Task\"
              }
            }
          }"

    - name: Optional: Send Slack Notification
      if: env.IS_NEW_VERSION == 'true'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        NEW_VERSION: ${{ env.NEW_VERSION }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"🔔 New Prometheus Helm Chart version available: *$NEW_VERSION*. JIRA ticket created.\"
        }" "$SLACK_WEBHOOK"
!= steps.get_current.outputs.current }}
        run: |
          ISSUE_SUMMARY="Update Prometheus Helm Chart to ${{ steps.get_latest.outputs.latest }}"
          ISSUE_DESCRIPTION="A new version of the Prometheus Helm chart is available.\n\n**Current version:** ${{ steps.get_current.outputs.current }}\n**Latest version:** ${{ steps.get_latest.outputs.latest }}\n\nPlease evaluate and upgrade if appropriate."

          curl --request POST \
            --url "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue" \
            --user "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "fields": {
                "project": {
                  "key": "'"${{ secrets.JIRA_PROJECT_KEY }}"'"
                },
                "summary": "'"$ISSUE_SUMMARY"'",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "text": "'"$ISSUE_DESCRIPTION"'",
                          "type": "text"
                        }
                      ]
                    }
                  ]
                },
                "issuetype": {
                  "name": "Task"
                }
              }
            }'
