name: Check Prometheus Helm Chart Version

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  check-helm-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Add Prometheus Community Helm repo
        run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Update Helm repos
        run: helm repo update

      - name: Get latest chart version
        id: get_latest
        run: |
          LATEST_VERSION=$(helm search repo prometheus-community/kube-prometheus-stack --versions -o json | jq -r '.[0].version')
          echo "latest=$LATEST_VERSION" >> "$GITHUB_OUTPUT"

      - name: Get current chart version
        id: get_current
        run: |
          CURRENT_VERSION=$(grep 'kube-prometheus-stack' path/to/your/helm/Chart.yaml | awk '{ print $2 }')
          echo "current=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create JIRA ticket if new version exists
        if: ${{ steps.get_latest.outputs.latest != steps.get_current.outputs.current }}
        run: |
          ISSUE_SUMMARY="Update Prometheus Helm Chart to ${{ steps.get_latest.outputs.latest }}"
          ISSUE_DESCRIPTION="A new version of the Prometheus Helm chart is available.\n\n**Current version:** ${{ steps.get_current.outputs.current }}\n**Latest version:** ${{ steps.get_latest.outputs.latest }}\n\nPlease evaluate and upgrade if appropriate."

          curl --request POST \
            --url "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue" \
            --user "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "fields": {
                "project": {
                  "key": "'"${{ secrets.JIRA_PROJECT_KEY }}"'"
                },
                "summary": "'"$ISSUE_SUMMARY"'",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "text": "'"$ISSUE_DESCRIPTION"'",
                          "type": "text"
                        }
                      ]
                    }
                  ]
                },
                "issuetype": {
                  "name": "Task"
                }
              }
            }'
